# Site settings
title: Community Health Explorer
baseurl: "/community-health-report" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Prose configuration
prose: 
  rooturl: "_data"
  ignore: ['/css', '/_includes', '/_layouts', '/scripts', '/', 'planning_district_boundaries.json', '*.yml', '*.geojson']

# Ruby config for plugins
#gems:
#  - octopress-paginate
#
#exclude:
#- Gemfile
#- Gemfile.lock
#- vendor
#- .travis.yml